### ISSUE TITLE
Issues with dead links on website, and ftp server.

### ISSUE THREAD

**Issue by mikedebian** [gnustep/gnustep.github.io#10]
http://wiki.gnustep.org/index.php/ times out.

Report Bugs on the mainpage, times out.

ftp.gnustep.org is down and has been for some time.

**Comment by ivucica** [comment]
The cause of this was that the old host has been shut down, and we were provided with a backup of our data, but not the software running on the machine.

ftp.gnustep.org has been available over FTP for a long time now, but I have only done work to enable access over HTTP today.

Based on some traces, it looks like the software running on the previous hosting provider was rather dated, and since we will not be risking running the old versions of PHP or MySQL, some code (including wiki) needs to be migrated to a version that can run with a more current version of PHP and MariaDB.

As adapting the database dump solely so it would run was quite involved, I had stopped work on this once I got the import to work. But, a newer version of MediaWiki still needs to be installed, the database imported, migrated to the newer schema, and so on. Therefore I am grabbing this issue to remind me that I need to migrate mediawiki.

**Comment by ivucica** [comment]
@dszidi Why did this get closed without discussion?

**Comment by gcasa** [comment]
This issue should be moved to https://github.com/gnustep/gnustep-www.

**Comment by ivucica** [comment]
Re-reading, this is indeed complete. Wiki is back up for a while now, and ftp is up as well.

**Comment by ivucica** [comment]
For future reference, given this is another configuration issue and regarding @gcasa comment in this thread https://github.com/gnustep/gnustep.github.io/issues/10#issuecomment-2248508968 :

I wrote a bit about `online-services-ops` repo: https://github.com/gnustep/gnustep.github.io/issues/6#issuecomment-2254262910
